package com.dambra.kotlinadvent.week1

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class RouteFinding {
    @Test
    fun `can route from start to finish with no obstacles`() {
        val route = """...........
        .......S...
        ...........
        ...........
        ...........
        ...........
        ..X........""".findRoute()

        assertThat(route).isEqualTo("""...........
.......*...
......*....
.....*.....
....*......
...*.......
..*........""")
    }

    @Test
    fun `can route around obstacles`() {
        val route = """....................
......X...B.........
..........B.........
........BBB....S....
....................""".findRoute()

        assertThat(route).isEqualTo(""".......****.........
......*...B*........
..........B.*.......
........BBB..***....
....................""")
    }

    @Test
    fun `can route around obstacles without leaving the map`() {
        val route = """......X...B.........
..........B.........
........BBB....S....
....................""".findRoute()
        assertThat(route).isEqualTo("""......*...B.........
.......*..B.........
.......*BBB*****....
........***.........""")
    }
}
